name: Security Gate

on:
  pull_request:
    branches: [main, secscan]

jobs:
  secrets-and-image-scan:
    name: "Secrets and Image Scan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: Set up Docker Buildx (if multi-arch support is ever needed)
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # Secret key leak scan
      - name: TruffleHog secrets scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: .

      # Build Docker image using Gradle task
      - name: Build Docker image with Gradle
        run: ./gradlew docker

      - name: List Docker images (debug)
        run: docker images

      # CVE Scan on that image
      - name: Grype image scan
        uses: anchore/scan-action@v3
        with:
          image: tolgee/tolgee
          fail-build: true
          output-format: sarif
          acs-report-enable: true

      # Upload SARIF to show alerts in PR
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: grype.sarif
