name: Gitleaks Secret Scan

on:
  push:
    branches: [ secscan ]
  pull_request:
    branches: [ secscan ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2