name: Gitleaks Secret Scan

on:
  push:
    branches: [ secscan ]
  #pull_request:
  #  branches: [ secscan ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          wget -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz
          tar -xvf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin

      - name: Run Gitleaks with custom rules on last 10 commits
        run: |
          N=10
          git log --pretty=format:"%H" --no-merges -n $N > commit_list.txt
          EXITCODE=0
          while read sha; do
            echo "Scanning commit $sha"
            gitleaks detect --commit=$sha --config=rules.yml --redact --exit-code=2 || EXITCODE=1
          done < commit_list.txt
          exit $EXITCODE